export default {

  fontSize: 10,
  fontFamily: 'arial, sans-serif',
  fontWeight: 'normal',
  fontStyle: 'normal',
  textAlign: 'left',
  width: 100,
  height: 100,
  color: 'black',
  borderColor: 'black',
  shadowColor: 'black',
  borderWidth: 0,
  shadowBlur: 0,
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  position: 'absolute',
  left: 0,
  bottom: 0,
  perspective: 100,
  opacity: 1,
  rotate: 0,
  scale: 1,
  blur: 0,
  gradientDirection: 0,
  gradientType: 'direction',
  gradient: {},
  pointerEvents: true,
  display: 'block',
  lineHeight: '100%',
  verticalAlign: 'top',
  zIndex: 0

};