import HANDLER_TOUCHSTART from './HANDLER.TOUCHSTART'
import HANDLER_TOUCHEND from './HANDLER.TOUCHEND'
import HANDLER_TOUCHMOVE from './HANDLER.TOUCHMOVE'
import HANDLER_MOUSEDOWN from './HANDLER.MOUSEDOWN'
import HANDLER_MOUSEUP from './HANDLER.MOUSEUP'
import HANDLER_MOUSEMOVE from './HANDLER.MOUSEMOVE'
import HANDLER_CLICK from './HANDLER.CLICK'
import HANDLER_DBLCLICK from './HANDLER.DBLCLICK'
import HANDLER_CONTEXTMENU from './HANDLER.CONTEXTMENU'

import HANDLER_KEYDOWN from './HANDLER.KEYDOWN'
import HANDLER_KEYUP from './HANDLER.KEYUP'
import HANDLER_KEYPRESS from './HANDLER.KEYPRESS'


export default {

  touchstart: HANDLER_TOUCHSTART,
  touchend: HANDLER_TOUCHEND,
  touchmove: HANDLER_TOUCHMOVE,
  mousedown: HANDLER_MOUSEDOWN,
  mouseup: HANDLER_MOUSEUP,
  mousemove: HANDLER_MOUSEMOVE,
  click: HANDLER_CLICK,
  dblclick: HANDLER_DBLCLICK,
  contextmenu: HANDLER_CONTEXTMENU,

  keydown: HANDLER_KEYDOWN,
  keyup: HANDLER_KEYUP,
  keypress: HANDLER_KEYPRESS

}